---

- name: get info from wp instance
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": WordPress Server
  register: wp_instance

- name: Add WordPress host to inventory with ip address
  add_host:
    name: "{{ wp_instance.instances[0].public_ip_address }}"
    groups: wordpress_host
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: "~/.ssh/key-cloud1.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: get info from mariadb instance
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": MariaDB Server
  register: mariadb_instance

- name: Add MariaDB host to inventory with ip address
  add_host:
    name: "{{ mariadb_instance.instances[0].public_ip_address }}"
    groups: mariadb_host
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: "~/.ssh/key-cloud1.pem"
    private_dns_name: "{{ mariadb_instance.instances[0].private_dns_name }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"