aws_access_key: ""
aws_secret_key: ""
key_name: "cloud1"
region: "eu-north-1"
image_id: "ami-01dad638e8f31ab9a"  # Utilisez l'AMI appropriée pour votre région et OS
instance_type: "t3.micro"
vpc_subnet_id: "default(omit)"
wp_user: "user"
wp_password: "password"
wp_database: "wordpress"
