---
# tasks file for launch_alb
- name: create a load balancer to target the wp autoscaling group  
  amazon.aws.elb_application_lb:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: wp_lb
    security_groups:
      - "{{ wp_instance.instances[0].security_groups.group_id }}"
    subnets:
      - "{{ wp_instance.instances[0].subnet_id }}"
    listeners:
      - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
        Port: 80 # Required. The port on which the load balancer is listening.
        # The security policy that defines which ciphers and protocols are supported. The default is the current predefined security policy.
        # SslPolicy: ELBSecurityPolicy-2015-05
        # Certificates: # The ARN of the certificate (only one certficate ARN should be provided)
          # - CertificateArn: arn:aws:iam::123456789012:server-certificate/test.domain.com
        DefaultActions:
          - Type: forward # Required.
            TargetGroupName: " {{ wp_tg.target_group_name }}" # Required. The name of the target group
    state: present